### ISSUE TITLE
Startscreen erstellen, bearbeiten, testen

### ISSUE THREAD

**Issue by xFuture603** [LazyProggers/project_zero#35]

**Comment by xFuture603** [comment]
Erstellen, bearbeiten und testen unseres Startscreens. Getestet werden Funktionalitäten der einzelnen Objekte, jedoch nicht das optische Aussehen. Der Startscreen erscheint derzeit direkt. Allerdings könnte man noch eine Szene davor schieben mit einer Animation.

**Comment by creyD** [comment]
Closed due ticket cleanup
