### ISSUE TITLE
Button Template/ Hauptmenü erstellen

### ISSUE THREAD

**Issue by creyD** [LazyProggers/project_zero#7]
GUI Hauptmenü entwerfen und funktionsfähig machen, Template zur Buttonerstellung erstellen.

**Comment by xFuture603** [comment]
Status: Erste Versuche mit Defold und hinzufügen von Funktionalitäten für die einzelnen Elemente, welche in der GUI verbaut sind

**Comment by xFuture603** [comment]
Arbeit fertig. Dadurch gibt es nun neue Probleme die es zu beheben gilt.
